import type { Metadata } from "next";
import { biz } from "./fonts";
import "./globals.css";
import Header from "./Header";
import { UiProvider } from "@/context/uiProvider";
import { Web3ContextProvider } from "@/context/web3Provider";

export const metadata: Metadata = {
  title: "NFT-zero",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={inter.className} className="flex"> */}
      <body className={`flex flex-col dark text-foreground bg-background ${biz.className}`}>
        <UiProvider>
          <Header></Header>
          <Web3ContextProvider>
            <main className="w-[1440px] flex flex-col flex-1">{children}</main>
          </Web3ContextProvider>
        </UiProvider>
      </body>
    </html>
  );
}
